### PR TITLE
Create zh_CN.lang

### PR DESCRIPTION
**Pull request by 3TUSK**

### CODE REVIEW

**Comment by TehNut** [comment]
why are you translators suddenly finding this project fascinating enough to translate?

**Comment by 3TUSK** [comment]
<s>Because</s>But I am also working on something like localization of Draconic Evolution... then I suddenly found something like this one. :)

Edit: Good mod for a modpack creator, isn't it?

**Comment by TehNut** [comment]
Nobody has touched translations for this in the entire time I've had it. Now two of you have submitted to this today. :P

This was actually made for @BBoldt's pack, albeit much more open than he originally wanted.

**Comment by BBoldt** [comment]
Is there actually a word for "goody" in Chinese?

xD

**Comment by TehNut** [comment]
Welp

BootyBags

**Comment by BBoldt** [comment]
https://youtu.be/znUS2KqPYCw?t=42

**Comment by 3TUSK** [comment]
Actually _nope_. However, I wanted to use "战利品袋子"(lit. loot bag) at first, but I remember that DartCraft has occupied this name in term of translation...
<s>"藏宝袋子" roughly means "treasure bag".</s>I will say this time google translator is _surprisingly_ right, but Chinese native speakers seem not to consider about whether it is stolen or not. Thus, if it is "宝藏袋子" (lit. treasure bag) it will be basically the same thing as well.
image
Why I use such a translation is that, I am sure that players will open it immediately as long as they see this name.

**Comment by 3TUSK** [comment]
Btw, would you mind talking about the plan about electro-magic tools? I know there is an unofficial continuation but what happened actually?

**Comment by TehNut** [comment]
Neither @Tombenpotter nor I had a wish to continue the project (We both dislike IC2 and it's API) so we dropped it. Fewizz has decided to maintain a fork of it. There is no passing of ownership.

Soon(tm) we will be working on an RF version of it with unique features.

**Pull request merged**
